# Generated by Django 4.1.5 on 2024-03-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=255)),
                ('msg_type', models.IntegerField(choices=[(1, 'Text'), (2, 'File'), (3, 'Image'), (4, 'Quote')])),
            ],
        ),
        migrations.CreateModel(
            name='UserLastRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
