# Generated by Django 4.1.5 on 2024-03-25 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlastroom',
            name='talker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.project'),
        ),
    ]
